export const CHECK_CALLSTACK = 'CHECK_CALLSTACK'
export const CHECK_FUNCTION = 'CHECK_FUNCTION'
export const ADD_TO_CALLSTACK = 'ADD_TO_CALLSTACK'
export const REMOVE_FROM_CALLSTACK = 'REMOVE_FROM_CALLSTACK'
