export const CHANGE_CALLSTACK_STATE = 'CHANGE_CALLSTACK_STATE'
export const CHECK_FUNCTION = 'CHECK_FUNCTION'
export const ADD_TO_CALLSTACK = 'ADD_TO_CALLSTACK'
export const REMOVE_FROM_CALLSTACK = 'REMOVE_FROM_CALLSTACK'
