export const editorTypes = {
	SET_DATA: 'SET_DATA',
	SET_EDITOR: 'SET_EDITOR',
	ADD_HIGHLIGHTED_LINE: 'ADD_HIGHLIGHTED_LINE',
	REMOVE_HIGHLIGHTED_LINE: 'REMOVE_HIGHLIGHTED_LINE',
	REMOVE_LAST_HIGHLIGHTED_LINE: 'REMOVE_LAST_HIGHLIGHTED_LINE',
	ADD_COLLAPSABLE_LINE: 'ADD_COLLAPSABLE_LINE',
	REMOVE_COLLAPSABLE_LINE: 'REMOVE_COLLAPSABLE_LINE',
}
